apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: worker-cpumanaged # The name of our custom pool
  labels:
    day: day2
    sample: cpupinning
spec:
  machineConfigSelector:
    matchExpressions:
      - key: machineconfiguration.openshift.io/role
        operator: In
        values:
          - worker            # Inherit standard worker configurations
          - worker-cpumanaged # Include custom configs specific to this pool
  nodeSelector:
    matchLabels:
      cpumanager: "true"      # Nodes with this label become part of this pool
  paused: false
